spring:
  datasource:
    url: TODO
    username: TODO
    password: 
    driver-class-name: org.h2.Driver
  hibernate:
    ddl-auto: validate
    
# Logging Configurations
 
#Monitoring endpoints   
management:
   endpoints:
      web:
         exposure:
            include: info, health