spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    initialization-mode: always    
    
  jpa: 
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: create-drop
    generate-ddl: false
    properties:
      hibernate:
        show_sql: true
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql
    
# sleuth custom propagation    
  sleuth:
    propagation-keys:
      - Media
      - Channel
      - UserId    
    log:
      slf4j:
        whitelisted-mdc-keys: 
          - Media
          - Channel
          - UserId
# request parameters and headers will be masked 
# turn to false to prevent unsafe logging of potentially sensitive data 
  http:
    log-request-details: true

#Monitoring endpoints   
management:
   endpoints:
      web:
         exposure:
            include: info, health, configprops, logfile, metrics, env, loggers
logging:
  level:
    org.springframework.boot.context.config.ConfigFileApplicationListener: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: INFO
    #org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.web.client: TRACE    
    org.springframework.web.servlet.DispatcherServlet: TRACE
    web: ERROR
