spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

  jpa: 
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: none
    generate-ddl: false
    properties:
      hibernate:
        show_sql: false

# Logging Configurations
logging:
  level:
    ROOT: INFO
#    org.springframework: INFO
    org.springframework.boot.context.config.ConfigFileApplicationListener: DEBUG
    org.springframework.boot.autoconfigure.batch: TRACE        

